-- Enregistrements pour la table gerants
-- 50 gerants : 40 maries (est_celibataire = FALSE), 7 celibataires, 3 statuts inconnus (NULL).
-- 10 valeurs inconnues pour nb_enfants (NULL).
-- Le nom Navet correspond a un legume present dans la table legumes.

INSERT INTO gerants (nom, prenom, email, nb_enfants, est_celibataire) VALUES
('Martin', 'Claire', 'claire.martin@example.com', 0, FALSE),
('Dubois', 'Julien', 'julien.dubois@example.com', 1, FALSE),
('Bernard', 'Sophie', 'sophie.bernard@example.com', 2, FALSE),
('Thomas', 'Lucas', 'lucas.thomas@example.com', 3, FALSE),
('Petit', 'Emma', 'emma.petit@example.com', 0, FALSE),
('Robert', 'Hugo', 'hugo.robert@example.com', 1, FALSE),
('Richard', 'Camille', 'camille.richard@example.com', 2, FALSE),
('Durand', 'Nathan', 'nathan.durand@example.com', 3, FALSE),
('Moreau', 'Lea', 'lea.moreau@example.com', 0, FALSE),
('Simon', 'Louis', 'louis.simon@example.com', 1, FALSE),
('Laurent', 'Chloe', 'chloe.laurent@example.com', 2, FALSE),
('Lefebvre', 'Noah', 'noah.lefebvre@example.com', 3, FALSE),
('Michel', 'Ines', 'ines.michel@example.com', 0, FALSE),
('Garcia', 'Arthur', 'arthur.garcia@example.com', 1, FALSE),
('David', 'Manon', 'manon.david@example.com', 2, FALSE),
('Bertrand', 'Ethan', 'ethan.bertrand@example.com', 3, FALSE),
('Roux', 'Alice', 'alice.roux@example.com', 0, FALSE),
('Vincent', 'Tom', 'tom.vincent@example.com', 1, FALSE),
('Fournier', 'Jade', 'jade.fournier@example.com', 2, FALSE),
('Morel', 'Lina', 'lina.morel@example.com', 3, FALSE),
('Girard', 'Leo', 'leo.girard@example.com', 4, FALSE),
('Andre', 'Louise', 'louise.andre@example.com', 5, FALSE),
('Lefevre', 'Gabriel', 'gabriel.lefevre@example.com', 6, FALSE),
('Mercier', 'Sarah', 'sarah.mercier@example.com', 4, FALSE),
('Dupont', 'Adam', 'adam.dupont@example.com', 5, FALSE),
('Dupont', 'Eva', 'eva.dupont@example.com', 6, FALSE),
('Dupont', 'Nina', 'nina.dupont@example.com', 4, FALSE),
('Lambert', 'Mael', 'mael.lambert@example.com', NULL, FALSE),
('Bonnet', 'Zoé', 'zoe.bonnet@example.com', NULL, FALSE),
('Francois', 'Paul', 'paul.francois@example.com', NULL, FALSE),
('Martinez', 'Mila', 'mila.martinez@example.com', NULL, FALSE),
('Legrand', 'Enzo', 'enzo.legrand@example.com', NULL, FALSE),
('Garnier', 'Lola', 'lola.garnier@example.com', NULL, FALSE),
('Faure', 'Sacha', 'sacha.faure@example.com', NULL, FALSE),
('Rousseau', 'Anna', 'anna.rousseau@example.com', NULL, FALSE),
('Blanc', 'Victor', 'victor.blanc@example.com', NULL, FALSE),
('Guerin', 'Iris', 'iris.guerin@example.com', NULL, FALSE),
('Navet', 'Oscar', 'oscar.navet@example.com', 2, FALSE),
('Perrin', 'Lucie', 'lucie.perrin@example.com', 1, FALSE),
('Morin', 'Raphael', 'raphael.morin@example.com', 0, FALSE),
('Riviere', 'Adele', 'adele.riviere@example.com', 0, TRUE),
('Chevalier', 'Bastien', 'bastien.chevalier@example.com', 1, TRUE),
('Clement', 'Margaux', 'margaux.clement@example.com', 2, TRUE),
('Gauthier', 'Nolan', 'nolan.gauthier@example.com', 3, TRUE),
('Roger', 'Elise', 'elise.roger@example.com', 0, TRUE),
('Colin', 'Mathis', 'mathis.colin@example.com', 1, TRUE),
('Marchand', 'Jeanne', 'jeanne.marchand@example.com', 2, TRUE),
('Dufour', 'Yanis', 'yanis.dufour@example.com', 3, NULL),
('Moulin', 'Clara', 'clara.moulin@example.com', 5, NULL),
('Renard', 'Samuel', 'samuel.renard@example.com', 4, NULL);