-- Enregistrements pour la table legumes
-- Valeurs kcal approximatives par 100 g, arrondies à l'entier.

INSERT INTO legumes (nom, kcal) VALUES
('Ail', 135),
('Artichaut', 40),
('Asperge', 25),
('Aubergine', 18),
('Betterave', 43),
('Blette', 20),
('Brocoli', 34),
('Carotte', 41),
('Celeri-branche', 16),
('Celeri-rave', 42),
('Champignon de Paris', 22),
('Chou blanc', 25),
('Chou rouge', 31),
('Chou frise', 49),
('Chou de Bruxelles', 43),
('Chou-fleur', 25),
('Concombre', 15),
('Courgette', 17),
('Cresson', 11),
('Echalote', 72),
('Endive', 17),
('Epinard', 23),
('Fenouil', 31),
('Haricot vert', 31),
('Laitue', 15),
('Mache', 19),
('Navet', 28),
('Oignon', 40),
('Panais', 75),
('Petit pois', 81),
('Poireau', 61),
('Poivron rouge', 31),
('Poivron vert', 20),
('Potiron', 26),
('Radis', 16),
('Rutabaga', 37),
('Salsifis', 82),
('Tomate', 18),
('Topinambour', 73),
('Mais doux', 86),
('Patate douce', 86),
('Pomme de terre', 77),
('Pois mange-tout', 42),
('Feve', 88),
('Lentille', 116),
('Pois chiche', 164),
('Haricot rouge', 127),
('Haricot blanc', 139),
('Roquette', 25),
('Igname', 118);
